## Basic initialization using empty() method

In [1]:
import torch

## 1-D vector
x = torch.empty(3)
print("1-D vector",x)


1-D vector tensor([-4.7349e-30,  1.7726e-42,  0.0000e+00])


In [2]:

## 2-D matrix
x1 = torch.empty(2,3)
print("\n 2-D matrix",x1)


 2-D matrix tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:

## 3-D matrix
x2 = torch.empty(2,2,3)
print("\n 3-D Matrix",x2)


 3-D Matrix tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [4]:

## 4-D matrix
x3 = torch.empty(2,2,3,3)
print(x3)

tensor([[[[-4.8565e-30,  1.7726e-42,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]],


        [[[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

         [[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]]])


## Other methods of initialization

In [5]:
y = torch.rand(2,4)
y

tensor([[0.9309, 0.5623, 0.5856, 0.3668],
        [0.3152, 0.6134, 0.7603, 0.8309]])

In [6]:
y1 = torch.ones(3,3,4)
y1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [7]:
y2 = torch.zeros(2,5)
y2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
## Initialization with a different data type

y3 = torch.ones(3,4, dtype=int)
y3

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [9]:
## Initialization with a different data type

y4 = torch.ones(3,4, dtype=torch.float)
y4

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
## Initialization with a different data type

y5 = torch.ones(3,4, dtype=torch.double)
y5

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

## Printing size of tensors

In [11]:
## Printing Size of tensor

print(y1.size())

torch.Size([3, 3, 4])


In [12]:
## Printing Size of tensor

print(x3.size())

torch.Size([2, 2, 3, 3])


## Conversion using tensor() method

In [13]:
## Converting a list to a tensor
n = torch.tensor([1,7,3,6])
n

tensor([1, 7, 3, 6])

## Arithmetic Operations

In [14]:
n1 = torch.rand(3,3)
n2 = torch.rand(3,3)

In [15]:
## Addition 
print(n1 + n2)
print(torch.add(n1,n2))

## ELement-Wise addition
print(n1.add_(n2))

tensor([[1.0384, 0.6252, 1.6387],
        [1.2425, 1.7163, 0.9605],
        [1.6831, 1.6358, 0.8109]])
tensor([[1.0384, 0.6252, 1.6387],
        [1.2425, 1.7163, 0.9605],
        [1.6831, 1.6358, 0.8109]])
tensor([[1.0384, 0.6252, 1.6387],
        [1.2425, 1.7163, 0.9605],
        [1.6831, 1.6358, 0.8109]])


In [16]:
## Subraction
print(n1 - n2)
print(torch.sub(n1, n2))

tensor([[0.8812, 0.4871, 0.9954],
        [0.8711, 0.7174, 0.2716],
        [0.9156, 0.7805, 0.2827]])
tensor([[0.8812, 0.4871, 0.9954],
        [0.8711, 0.7174, 0.2716],
        [0.9156, 0.7805, 0.2827]])


In [17]:
## Multiplication

print(n1 * n2)
print(torch.mul(n1, n2))

tensor([[0.1633, 0.0864, 1.0541],
        [0.4616, 1.7144, 0.6616],
        [1.2917, 1.3989, 0.4284]])
tensor([[0.1633, 0.0864, 1.0541],
        [0.4616, 1.7144, 0.6616],
        [1.2917, 1.3989, 0.4284]])


In [18]:
## Division

print(n1 / n2)
print(torch.div(n1, n2))

tensor([[6.6055, 4.5250, 2.5475],
        [3.3449, 1.7181, 1.3943],
        [2.1931, 1.9127, 1.5351]])
tensor([[6.6055, 4.5250, 2.5475],
        [3.3449, 1.7181, 1.3943],
        [2.1931, 1.9127, 1.5351]])


## Indexing Tensors

In [19]:
print(n1, n1.shape)
print("\n first row",n1[0, :])
print("\n first column",n1[:, 0])

tensor([[1.0384, 0.6252, 1.6387],
        [1.2425, 1.7163, 0.9605],
        [1.6831, 1.6358, 0.8109]]) torch.Size([3, 3])

 first row tensor([1.0384, 0.6252, 1.6387])

 first column tensor([1.0384, 1.2425, 1.6831])


## View function to display the tensor

In [25]:
n1.view(-1, 3)

tensor([[1.0384, 0.6252, 1.6387],
        [1.2425, 1.7163, 0.9605],
        [1.6831, 1.6358, 0.8109]])

In [27]:
n1.view(-1, 1)

tensor([[1.0384],
        [0.6252],
        [1.6387],
        [1.2425],
        [1.7163],
        [0.9605],
        [1.6831],
        [1.6358],
        [0.8109]])

In [28]:
n2.view(-1, 9)

tensor([[0.1572, 0.1382, 0.6432, 0.3715, 0.9989, 0.6889, 0.7674, 0.8552, 0.5283]])

In [29]:
import numpy
import torch

In [31]:
## Creating a new tensor
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [35]:
## Creating a new numpy array
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [36]:
## Adding one to all elements of tensor 
a.add(1)

tensor([2., 2., 2., 2., 2.])

In [38]:
## printing numpy array after addition operation to tensor
print(b)

## Refer the following markdown

[1. 1. 1. 1. 1.]


If the add() function has an effect on the numpy array, then they both might be assigned to the same memory location which will make the changes to both the arrays.

In [39]:
## Moving the data to the GPU then performing the operations
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device = device)
    y = torch.ones(5)
    y = y.to(device)
    z = x+y

In [40]:
## Numpy can only handle tensors on CPU which causes the errror.
z.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [41]:
## Moving tensor back to CPU from GPU
z = z.to("cpu")

In [42]:
## After moving the CPU now the tensor gets accessible by the numpy
z.numpy()

array([2., 2., 2., 2., 2.], dtype=float32)

In [44]:
## requires_grad -> tells pytorch that it will need to calculate the gradient to this tensor later in the optimization step
x = torch.ones(5, requires_grad=True)

In [45]:
## Whenever we need to optimize a variable, we have to specify this
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)