## Gradient Calculation with AutoGrad

In [1]:
## Can be used for calculating gradients, which are essential for model optimization

In [2]:
import torch

In [3]:
x = torch.rand(3, requires_grad=True)
x

tensor([0.6718, 0.6923, 0.5786], requires_grad=True)

In [4]:
y = x+2
y

tensor([2.6718, 2.6923, 2.5786], grad_fn=<AddBackward0>)

In [5]:
z = y*y*2
z

tensor([14.2766, 14.4965, 13.2979], grad_fn=<MulBackward0>)

In [6]:
z = z.mean()
z

tensor(14.0237, grad_fn=<MeanBackward0>)

In [7]:
## Computing gradient 
z.backward()
print(x.grad)

tensor([3.5624, 3.5897, 3.4381])


In [9]:
## Preventing Gradient history